version: '3'

services:
  pgsql:
    image: postgres:13-alpine
    container_name: db_pgsql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mydev
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./pgsql/initdb:/docker-entrypoint-initdb.d
      - ./pgsql/datadir:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: web_pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@jcble.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
    links:
      - pgsql
    restart: always